# -*- coding: utf-8 -*-
"""App Movie recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U42tR1KTAQt77vVPCZ7FrwVW2cbOitGw
"""

import numpy as np #importing dependencies
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import streamlit as st
movies_data = pd.read_csv('movies.csv')#loading data from csv file to a pandas dataframe
selected_features = ['genres', 'keywords', 'tagline', 'cast', 'director']
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('') #replacing null values with null string
combined_features = movies_data['genres'] + ' ' + movies_data['keywords'] + ' ' + movies_data['tagline'] + ' ' + movies_data['cast'] + ' ' + movies_data['director']
vectorizer = TfidfVectorizer()#converting text data to feature vectors
feature_vectors = vectorizer.fit_transform(combined_features)
similarity = cosine_similarity(feature_vectors) #getting similarity scores
st.title("🎬 Movie Recommendation System")
movie_name = st.text_input('Enter your favorite movie name: ') #taking movie name as input from user
if st.button('Recommend'):
  list_of_all_titles = movies_data['title'].tolist()#creating list of all movie names given in dataset
  find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)#finding closest match for input movie name
  if find_close_match:
    close_match = find_close_match[0]
    index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
    similarity_score = list(enumerate(similarity[index_of_the_movie]))#getting list of similar movies
    sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) # sorting movies based on similarity score
    st.write('Movies suggested for you: \n') #print names of similar movies based on index
    i = 1
    for movie in sorted_similar_movies:
      index = movie[0]
      title_from_index = movies_data.iloc[index]['title']
      if i < 11: 
          st.write(i, title_from_index)
          i = i + 1
          
    









