# -*- coding: utf-8 -*-
"""app 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ei8d-iJjW3SZdg-FrkKp8A_7RrxhQwvN
"""

import numpy as np
import pandas as pd
import difflib
import requests
import streamlit as st

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ---------------- YOUR ORIGINAL CODE ----------------

movies_data = pd.read_csv('movies.csv')

selected_features = ['genres','keywords','tagline','cast','director']

for feature in selected_features:
    movies_data[feature] = movies_data[feature].fillna('')

combined_features = (
    movies_data['genres'] + ' ' +
    movies_data['keywords'] + ' ' +
    movies_data['tagline'] + ' ' +
    movies_data['cast'] + ' ' +
    movies_data['director']
)

vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)

similarity = cosine_similarity(feature_vectors)

list_of_all_titles = movies_data['title'].tolist()

# ---------------- POSTER FUNCTION ----------------

def fetch_poster(movie_name):

    api_key = "YOUR_TMDB_API_KEY"

    url = f"https://api.themoviedb.org/3/search/movie?api_key={api_key}&query={movie_name}"

    data = requests.get(url).json()

    if data["results"]:
        poster_path = data["results"][0]["poster_path"]
        return "https://image.tmdb.org/t/p/w500/" + poster_path

    return None


# ---------------- STREAMLIT UI ----------------

st.title("🎬 AI Movie Recommendation System")

movie_name = st.text_input("Enter your favourite movie")

if st.button("Recommend"):

    find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

    if find_close_match:

        close_match = find_close_match[0]

        index_of_movie = movies_data[movies_data.title == close_match]['index'].values[0]

        similarity_score = list(enumerate(similarity[index_of_movie]))

        sorted_movies = sorted(similarity_score, key=lambda x:x[1], reverse=True)

        st.subheader("Recommended Movies")

        cols = st.columns(5)

        i = 0

        for movie in sorted_movies[1:11]:

            index = movie[0]
            title = movies_data.iloc[index]['title']

            poster = fetch_poster(title)

            with cols[i % 5]:
                if poster:
                    st.image(poster)
                st.write(title)

            i += 1